### ISSUE TITLE
Java property name doesn't match its field name

### ISSUE THREAD

**Issue by yayj** [cvrabie/protobuf2hibernate#1]
The c-style variable like "foo_bar" in .proto file will be translated into "fooBar" while compiling to be corresponding to java-style. ProtobufTuplizer uses "foo_bar" to store the mapping table in ProtobufTuplizer.fieldCacheByName but accepting "fooBar" to querying.
So, if underscore '_' is present in .proto file, ProtobufTuplizer will throw a HibernateException to indicate "Property descriptor can' be null!".

It might be a possible way to unify the key format in ProtobufTuplizer.fieldCacheByName. Using java-style might be better than c-style since ProtobufTuplizer.getPropertyValue and ProtobufTuplizer.setPropertyValue both accept java-style property name.

**Comment by ghost** [comment]
so is this issue solved? cos i have some more :D

**Comment by yayj** [comment]
@vach I think my PR #2 had fixed it already.
